Feat/apolloserver
Videiraft/curious-server pull request #3
Opened 2019-08-13 18:25 UTC by Videiraft

2019-08-13 18:36 UTC, raketeFlo requested changes
- looks good so far --> just the JWT token I would do this outside of app.js and import later
- let us not forget the error handling for the login -> so far we only have a console.log statement

2019-08-13 18:36 UTC, steelersbcn commented on app.js
> +function getUser(rawToken) {
I would not do this in app.js but create a util function and import it then

2019-08-13 18:36 UTC, steelersbcn commented on app.js
> +  if (rawToken.length) {
same here

2019-08-13 18:36 UTC, steelersbcn commented on graphQL/resolvers/mutations.resolvers.js
> +    console.log('email already exists'); // eslint-disable-line no-console
should be "user does not exist" like you did on line 31

2019-08-13 18:47 UTC, RobAntunes commented on graphQL/resolvers/mutations.resolvers.js
> +exports.createRoadmap = async (obj, args) => {
How are we error-handling this? (29 - 41). Probably reoccurs resolvers.

2019-08-13 18:53 UTC, RobAntunes commented on graphQL/resolvers/queries.resolvers.js
> +exports.user = async (obj, { email, password }) => {
Inconsistency: "args" not usually deconstructed within parameters.

2019-08-14 13:09 UTC, marcoantonioghiani01 commented on app.js
> +  context: ({ req }) => {
The logic to return the middleware could be extracted in an external function.

2019-08-14 13:09 UTC, marcoantonioghiani01 commented on graphQL/resolvers/mutations.resolvers.js
> +  if (!user) throw new AuthenticationError('You must be logged in');
Are you sure is necessary to repeat this check for all the resolvers? Maybe there is a better way to define a protected route in graphql. Follow [this guide](https://medium.com/the-guild/authentication-and-authorization-in-graphql-and-how-graphql-modules-can-help-fadc1ee5b0c2) to get a better idea about a _guard_.

2019-08-15 09:50 UTC, marcoantonioghiani01 commented on graphQL/resolvers/mutations.resolvers.js
> +  return 'item deleted';
Would be better to return the id of the deleted item, so that you can remove it from the list of checks you have in the client

2019-08-15 09:50 UTC, marcoantonioghiani01 commented on graphQL/resolvers/queries.resolvers.js
> +  if (args.id === user.id) {
Use loose equality to enable coercion on this comparison.

2019-08-19 16:38 UTC, raketeFlo approved these changes

2019-08-19 16:39 UTC, andre-coutinho approved these changes

2019-08-19 16:39 UTC, merged